services:
  - type: web
    name: recipeshare
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn recipeshare.wsgi:application"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: ENVIRONMENT
        value: production